[window]
blur=true
opacity=0.7

[font]
normal = { family = "IBM Plex Mono", style = "Regular" }

[colors.primary]
background = "#1b1f1a"
foreground = "#e6e2d6"

[colors.cursor]
text = "#1b1f1a"
cursor = "#8fa88a"

[colors.selection]
text = "#e6e2d6"
background = "#3f5e4a"

[colors.normal]
black   = "#1b1f1a"
red     = "#a4636a"
green   = "#6f8f6a"
yellow  = "#c4a86a"
blue    = "#7aa6a1"
magenta = "#b07d5a"
cyan    = "#8fa88a"
white   = "#c9c2b3"

[colors.bright]
black   = "#242a23"
red     = "#b77a80"
green   = "#86a780"
yellow  = "#d6bf86"
blue    = "#90beb8"
magenta = "#c6946b"
cyan    = "#a8c2a2"
white   = "#e6e2d6"
